### PR TITLE
Rename and Enhance Action Trigger Documentation: Add Cloning Steps, Tips and Warnings

### PR DESCRIPTION
**Pull request by IanSkelskey**
> This change came out of Bibliomation's recent struggles to get push notifications set up. The problem ended up being our environment was misconfigured. We could have avoided a lot of pain if we started from a clone of an existing working action trigger instead of starting from scratch. By environment, I am referring to the action trigger's environment, not the general dev or production environment.
image
This change may be more opinionated than my previous ones, so feel free to provide feedback and I can adjust as needed. Though I will say that the Evergreen docs themselves also recommend against creating action triggers from scratch.

Renames the \"create-an-action-trigger.md\" file to \"configure-evergreen.md\" to better reflect its content. Enhances documentation by adding detailed procedures for cloning and creating action triggers with reminders and warnings. Links to a newly added sample template subsection for better guidance.

- Guide title changed to \"Configure Evergreen Action Triggers\"
- Added sections on cloning and creating action triggers from scratch
- Included tips and warnings for best practices
- Provided a link to the Evergreen Action Trigger documentation for additional help

### CODE REVIEW

**Comment by IanSkelskey** [comment]
P.S. The Evergreen action trigger docs need an update too. I'm working on that, but it may take a little while. (Either way, the link I added to your docs here should remain valid and they are still better than nothing)

**Review by kenstir — CHANGES_REQUESTED** [review]
Thanks, Ian, this looks good.  If you would please fix the broken link caused by the rename I will merge it.

**Comment by IanSkelskey** [comment]
> Thanks, Ian, this looks good. If you would please fix the broken link caused by the rename I will merge it.

No problem. Sorry I missed that.

**Comment by IanSkelskey** [comment]
Should be all set now.

**Pull request merged**
